# Generated by Django 2.0.3 on 2018-03-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteins', models.IntegerField()),
                ('fat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
